root: true
env:
  browser: true
settings:
  react:
    version: detect
plugins:
  - editorconfig
  - sonarjs
extends:
  - eslint:recommended
  - xo
  - xo-react
  - plugin:editorconfig/all
  # - plugin:sonarjs/recommended
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  react/no-array-index-key: off
  react/require-default-props: off
  object-shorthand: off
  capitalized-comments: off
  implicit-arrow-linebreak:
    - error
    - beside
  guard-for-in: off

overrides:
  - files:
      - "*.json"
    plugins:
      - json
    extends:
      - plugin:json/recommended

  - files:
      - tokens/**/*.js
    env:
      node: true
    rules:
      sonarjs/no-duplicate-string: off

  - files:
      - "*.@(yml|yaml)"
    plugins:
      - yaml
    extends:
      - plugin:yaml/recommended

  - files:
      - "*.@(ts|tsx)"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project:
        - ./tsconfig.json
    plugins:
      - "@typescript-eslint"
    extends:
      - plugin:@typescript-eslint/recommended
      - xo-typescript
    rules:
      "@typescript-eslint/ban-types": off
      "@typescript-eslint/consistent-type-assertions": off
      "@typescript-eslint/naming-convention": off

  - files:
      - src/**/*.stories.@(ts|tsx)
    extends:
      - plugin:storybook/recommended
    rules:
      react-hooks/rules-of-hooks: off

ignorePatterns:
  - "*.md"
  - "*.mdx"
