env:
  browser: true
root: true
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:editorconfig/all
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - editorconfig
  - "@typescript-eslint"
rules:
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  implicit-arrow-linebreak:
    - "error"
    - "beside"
ignorePatterns:
  - "*.md"
  - "*.mdx"
