env:
  browser: true
root: true
settings:
  react:
    version: detect
plugins:
  - sonarjs
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - plugin:sonarjs/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  implicit-arrow-linebreak:
    - error
    - beside
overrides:
  - files:
      - "tokens/**/*.js"
    env:
      node: true
  - files:
      - "(src|scripts)/**/*.(ts|tsx)"
      - "**/*.tsx"
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
ignorePatterns:
  - "*.md"
  - "*.mdx"
