import { type SubmitHandler } from 'react-hook-form';
import { type FormData } from './index';

export const onValid: SubmitHandler<FormData> = data => {
	console.log(data);

	// 	event.preventDefault();

	// 	const formData = new FormData(event.currentTarget);

	// 	/*
	// 			NPM - EXAMPLE:
	// 			content-type-input: "name"
	// 			deadline-input: "2023-06-15"
	// 			email-input: "test@email.com"
	// 			material-type-input: "sash"
	// 			name-input: "test name"
	// 			quantity-input: "10"
	// 			service-type-input: "embroider"
	// 		*/

	// 	const mailTo = 'hello.crealgo@gmail.com';

	// 	const contentType = formData.get('content-type-input')?.toString() ?? '';
	// 	const deadline = formData.get('deadline-input')?.toString() ?? '';
	// 	const email = formData.get('email-input')?.toString() ?? '';
	// 	const materialType = formData.get('material-type-input')?.toString() ?? '';
	// 	const name = formData.get('name-input')?.toString() ?? '';
	// 	const quantity = formData.get('quantity-input')?.toString() ?? '';
	// 	const serviceType = formData.get('service-type-input')?.toString() ?? '';

	// 	const subject = encodeURIComponent(
	// 		`Estimate Request request for a ${materialType}`
	// 	);
	// 	const body = encodeURIComponent(`Hi, I'm ${name}!
	// I'd like to get an estimate for a ${serviceType}. Here are my details:

	// Customer Info
	// Customer Name: ${name}
	// Customer Email: ${email}
	// Content Type: ${contentType}
	// By Deadline: ${deadline}
	// Material Type: ${materialType}
	// Quantity: ${quantity}
	// Service Type: ${serviceType}

	// Attach your image or artwork below:
	// ///// Replace with Image or Artwork 🖼️ /////

	// Thanks,
	// ${name}

	// Generated by the 🤖 Crealgo Bot`);

	// 	location.href = `mailto:${mailTo}?subject=${subject}&body=${body}`;
};
