name: Deploy Graphix Collab Static Site

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deployment_type:
        type: choice
        description: Environment Type
        options:
          - development
          - staging
          - production

permissions:
  contents: write

env:
  AUTHOR_NAME: 🤖 Crealgo Bot
  AUTHOR_EMAIL: bot.crealgo@gmail.com

  STATIC_BUILD_EXPORT_PATH: out
  STATIC_BUILD_NAME: static-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Verify
        run: npm run verify

      - name: Build Development App
        if: ${{ github.event_name == 'push' || inputs.deployment_type == 'development' }}
        env:
          ASSET_PREFIX:  "."
          BASE_PATH: /grahpixcollab
          NEXT_PUBLIC_PROJECT_ID: graphixcollab
          NEXT_PUBLIC_API_URL: https://api.crealgo.com
          NEXT_PUBLIC_API_ID: graphix-collab
        run: |
          npx next build --no-lint
          npx next export -o ${{ env.STATIC_BUILD_EXPORT_PATH }}

      # upload artifeact
      - name: Save Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_BUILD_NAME }}
          path: ${{ env.STATIC_BUILD_EXPORT_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Build Folder
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.STATIC_BUILD_NAME }}

      # Always auto-deploy development
      - name: Deploy Site to Development
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: ${{ env.AUTHOR_NAME }}
          user_email:  ${{ env.AUTHOR_EMAIL }}
          external_repository: crealgo/crealgo-static-projects
          publish_dir: ${{ steps.download.outputs.download-path }}
          destination_dir: graphixcollab
