name: Deploy Graphix Collab Static Site

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deployment_type:
        type: choice
        description: Environment Type
        options:
          - development
          - staging
          - production

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Setup Repository
        run: npm ci

      - name: Build Development App
        env:
          ASSET_PREFIX:  "."
          BASE_PATH: /grahpixcollab
          NEXT_PUBLIC_PROJECT_ID: graphixcollab
          NEXT_PUBLIC_API_URL: https://api.crealgo.com
          NEXT_PUBLIC_API_ID: graphix-collab
        run: npm run site:build

      - if: ${{ inputs.deployment_type == 'staging' || inputs.deployment_type == 'production' }}
        name: Build Staging/Production App
        env:
          ASSET_PREFIX:  "."
          BASE_PATH:
          NEXT_PUBLIC_PROJECT_ID: graphixcollab
          NEXT_PUBLIC_API_URL: https://api.crealgo.com
          NEXT_PUBLIC_API_ID: graphix-collab
        run: npm run site:build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Site to Development
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: Crealgo Bot 🤖
          user_email: hello.crealgo@gmail.com
          external_repository: crealgo/crealgo-static-projects
          publish_dir: out
          destination_dir: graphixcollab

      - if: ${{ inputs.deployment_type == 'staging' || inputs.deployment_type == 'production' }}
        name: Deploy Site to Staging
        uses: peaceiris/actions-gh-pages@v3
        env:
          CNAME_URL: ${{ inputs.deployment_type == 'staging' && 'beta.' || '' }}graphixcollab.com
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: Crealgo Bot 🤖
          user_email: hello.crealgo@gmail.com
          external_repository: crealgo/graphixcollab-static-${{ inputs.deployment_type}}
          publish_dir: out
          cname: ${{ env.CNAME_URL }}
