name: Deploy Graphix Collab Static Site

on:
  push:
    branches:
      - main

  # workflow_dispatch:
  #   inputs:
  #     deployment_type:
  #       type: choice
  #       description: Environment Type
  #       options:
  #         - development
  #         - staging
  #         - production

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Setup Repository
        run: npm ci

      - name: Build Next App
        env:
          BASE_PATH: /crealgo
          ASSET_PREFIX:  "."
          NEXT_PUBLIC_PROJECT_ID: graphixcollab
          NEXT_PUBLIC_API_URL: https://api.crealgo.com
          NEXT_PUBLIC_API_ID: graphix-collab
        run: npm run site:build

      - name: Deploy Storybook to Development
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: Crealgo Bot 🤖
          user_email: hello.crealgo@gmail.com
          external_repository: crealgo/crealgo-static-projects
          publish_dir: out
          destination_dir: graphixcollab
