name: Build and Deploy Site

on:
  push:
    branches: ["main"]

  workflow_run:
    workflows: ["Scrape Yelp Data"]
    branches: ["main"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'staging'
        type: environment

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm clean-install

      - name: Verify
        run: npm run verify

      - name: Build App
        env:
          NEXT_PUBLIC_API_URL: https://test.crealgo.com/v1
          NEXT_PUBLIC_APP_ID: graphixcollab
        run: npm run site:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.event.inputs.environment }}
          path: out
          if-no-files-found: error
          overwrite: true

  deploy:
    needs: build
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ vars.DEPLOYMENT_URL }}

    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages-${{ github.event.inputs.environment }}
          path: upload

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: 🤖 Crealgo Bot
          user_email: bot.crealgo@gmail.com
          external_repository: ${{ vars.DEPLOYMENT_REPOSITORY }}
          cname: ${{ vars.CNAME }}
          publish_dir: upload
