name: Deploy Hydra React Storybook

on:
  push:
    branches:
      - main
    paths-ignore:
      -  "pages/**"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Setup Repository
        run: npm i

      - name: Verify
        run: npm run verify

      - name: Build Storybook
        run: npx storybook build -s public

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: Crealgo Bot 🤖
          user_email: hello.crealgo@gmail.com
          external_repository: crealgo/crealgo-static
          publish_dir: storybook-static
          destination_dir: ./component-library

