name: 🚀 Trigger Deploy

on:
  push:
    branches: ["main"]

  workflow_run:
    workflows: ["Scrape Yelp Data"]
    branches: ["main"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "staging"
        type: environment

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "URL: ${{ vars.DEPLOYMENT_URL }}"
          echo "Repository: ${{ vars.DEPLOYMENT_REPOSITORY }}"
          echo "CNAME: ${{ vars.CNAME }}"

  use-staging:
    if: github.event_name == 'push' || github.event_name == 'workflow_run'
    uses: crealgo/graphixcollab-frontend-react/.github/workflows/deploy-site.yml@main
    secrets: inherit
    with:
      environment: staging
      url: https://graphixcollab.crealgo.dev/
      repository: crealgo/graphixcollab-static-staging
      cname: graphixcollab.crealgo.dev

  use-dynamic:
    if: github.event_name == 'workflow_dispatch'
    uses: crealgo/graphixcollab-frontend-react/.github/workflows/deploy-site.yml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      url: ${{ vars.DEPLOYMENT_URL }}
      repository: ${{ vars.DEPLOYMENT_REPOSITORY }}
      cname: ${{ vars.CNAME }}
