name: Build and Deploy Staging Site

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

  workflow_run:
    workflows: ["Scrape Yelp Data"]
    branches: ["main"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Verify
        run: npm run verify

      - name: Build App
        env:
          NEXT_PUBLIC_API_URL: https://api.crealgo.com/v1
          NEXT_PUBLIC_APP_ID: graphixcollab
        run: npm run build

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: 🤖 Crealgo Bot
          user_email: bot.crealgo@gmail.com
          external_repository: crealgo/graphixcollab-static-staging
          cname: graphixcollab.crealgo.dev
          publish_dir: out
