name: Build and Deploy Site
run-name: Build and Deploy to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: staging
        type: string
      url:
        description: 'The URL of the deployment'
        required: true
        type: string
      repository:
        description: 'The repository to deploy to'
        required: true
        type: string
      cname:
        description: 'The custom domain to use'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm clean-install

      - name: Verify
        run: npm run verify

      - name: Build App
        env:
          NEXT_PUBLIC_API_URL: https://test.crealgo.com/v1
          NEXT_PUBLIC_APP_ID: graphixcollab
        run: npm run site:build

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: 🤖 Crealgo Bot
          user_email: bot.crealgo@gmail.com
          external_repository: ${{ inputs.repository }}
          cname: ${{ inputs.cname }}
          publish_dir: ./out
