name: Scrape Yelp Data

on:
  schedule:
    # cron everyday at midnight
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Setup Repository
        run: npm ci

      - name: Scrape
        run: npx tsx scripts/scrape-yelp-reviews.ts

      - name: Commit and Push Yelp Data
        run: |
          git config --local user.email "hello.crealgo@gmail.com"
          git config --local user.name "🤖 Crealgo Bot"
          git add .
          git commit -m "perf(Yelp): update latest Yelp reviews"