name: Build and Deploy Prod/Staging Site

on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Deployment Type'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

permissions:
  contents: write

env:
  AUTHOR_NAME: 🤖 Crealgo Bot
  AUTHOR_EMAIL: bot.crealgo@gmail.com

  CREALGO_APP_ID: graphixcollab

  DOMAIN: ${{ inputs.deployment-type == 'staging' && 'graphixcollab.crealgo.dev' || 'graphixcollab.com' }}
  CREALGO_REPOSITORY: crealgo/graphixcollab-static-${{ inputs.deployment-type }}

run-name: Build and Deploy ${{ inputs.deployment-type == 'staging' && 'Staging' || 'Production' }} Site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Verify
        run: npm run verify

      - name: Build App
        env:
          NEXT_PUBLIC_API_URL: https://api.crealgo.com
          NEXT_PUBLIC_APP_ID: ${{ env.CREALGO_APP_ID }}
        run: |
          npx next build --no-lint
          npx next export

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          user_name: ${{ env.AUTHOR_NAME }}
          user_email:  ${{ env.AUTHOR_EMAIL }}
          external_repository: ${{ env.CREALGO_REPOSITORY }}
          cname: ${{ env.DOMAIN }}
          publish_dir: out
